Removing the lock (Do not merge yet)
sapcc/networking-arista pull request #8
Opened 2018-05-08 11:50 UTC by fwiesel

2018-05-08 14:30 UTC, notandy requested changes

2018-05-08 14:30 UTC, notandy commented on networking_arista/ml2/mechanism_arista.py
> +        self._try_to_release_dynamic_segment(plugin_context)
Sure what you want to pass plugin_context? unit tests fail because it cannot access host of context._plugin_context

2018-05-08 14:30 UTC, notandy commented on networking_arista/ml2/mechanism_arista.py
> -            if db_lib.is_port_provisioned(port_id):
No check for is_port_provisioned anymore, is this intended?

2018-05-09 08:30 UTC, fwiesel commented on networking_arista/ml2/mechanism_arista.py
> -            if db_lib.is_port_provisioned(port_id):
Ah, no. It looks like I deleted one line more than intended

2018-05-09 08:31 UTC, fwiesel commented on networking_arista/ml2/mechanism_arista.py
> +        self._try_to_release_dynamic_segment(plugin_context)
Probably not. My idea was to pass "context" to all mechanism_arista objects, and to db_lib the plugin_context.

2018-05-10 11:55 UTC, fwiesel commented on networking_arista/ml2/mechanism_arista.py
> -            if db_lib.is_port_provisioned(port_id):
Now, I remember. The check is superfluous, as the delete operation will simply delete nothing, if there is no row matching the query, so it is a no-op.

2018-05-10 12:21 UTC, fwiesel commented
I think, all the theoretical issues are fixed. We now just need to test it physically.

2018-05-14 06:59 UTC, merged